//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsaNews24h.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class states_list
    {
        public int id { get; set; }
        public string state { get; set; }
        public string capital { get; set; }
        public string largestcity { get; set; }
    }
}
